include ../common/config.mk

TARGET := libkbinput.so
CXXFLAGS := $(CXXFLAGS) -fpic 
LDFLAGS := $(LDFLAGS) -lSDL -lSDL_ttf -lSDL_image -lrt -shared

include ../common/commands.mk
include ../common/recipes.mk