include ../common/config.mk

TARGET = batteryMonitorUI
CFLAGS := $(CFLAGS) $(SDL_FLAGS)
LDFLAGS := $(LDFLAGS) -lSDL -lSDL_image -lSDL_ttf -lsqlite3

include ../common/commands.mk
include ../common/recipes.mk
